[loadbalancer]
machine_a ansible_host=34.9.148.170 ansible_user=ubuntu ansible_ssh_private_key_file=./akm-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers]
machine_b ansible_host=192.168.0.20 ansible_user=ubuntu ansible_ssh_private_key_file=./akm-key.pem
machine_c ansible_host=192.168.0.30 ansible_user=ubuntu ansible_ssh_private_key_file=./akm-key.pem

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@34.9.148.170 -i ./akm-key.pem -o StrictHostKeyChecking=no" -o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3